### ISSUE TITLE
EXODUS error and CalculiX extras exodus

### ISSUE THREAD

**Issue by 3rav** [gsjaardema/seacas#119]
Hi, 

In the CalculiX [http://calculix.de/](url) FEA program with an add-on [https://www.openaircraft.com/calculix-extras/](url) that allows saving results to a .exo file, there are such warnings/errors:

```
Exodus Library Warning/Error: [ex_get_time]
	ERROR: time_step is out-of-range. Value = 0, valid range is 1 to 0 in file id 65536
```

or 

```
Exodus Library Warning/Error: [ex_put_variable_param]
	ERROR: nodal variable name parameters are already defined in file id 65536
	NetCDF: String match to name in use
```

**Comment by gsjaardema** [comment]
I took a look at the `ccx_extras.2.13.exo.patch`.  I think the `ex_get_time` issue is shown below:
```
+  /* Start the data storage section */
+  float version;
+  exoid = ex_open (fneig, /*Filename*/
+		   EX_WRITE,	/* create mode */
+		   &CPU_word_size,  /* CPU float word size in bytes */
+		   &IO_word_size, /* I/O float word size in bytes */
+		   &version);
+
+  // Define an output variable for general use
+  float *nodal_var_vals;
+
+  int num_time_steps;
+  float fdum;
+  char cdum = 0;
+
+  float timet;
+  errr = ex_inquire (exoid, EX_INQ_TIME, &num_time_steps, &fdum, &cdum);
+  errr = ex_get_time (exoid, num_time_steps, &timet);
+  if (num_time_steps>0){
+    printf ("\t%i Time periods in exo file, most recent at time=%f\n", num_time_steps, timet);
+  } else {
+    printf ("\t0 Time periods in exo file\n");
+  }
```
Following the `ex_inquire` call, the app needs to check that `num_time_steps > 0` before calling `ex_get_time`.    I will fix the error message to make it more clear that there are no timesteps on the model instead of the current message with non-sensical valid range output.

I think the second error is due to trying to define nodal variables in a file where the nodal variables are already defined.  I haven't looked in depth at the CalculiX code to see where this is happening, but it may be possible to check whether any variables are defined prior to defining them...

**Comment by gsjaardema** [comment]
NOTE: The URLs in the original bug report don't resolve correctly.  Use the following instead: http://calculix.de/, and https://www.openaircraft.com/calculix-extras/

**Comment by 3rav** [comment]
For the latest version of the exodus (20.10.2018), there are such messages:

```
Exodus Library Warning/Error: [ex_put_nodal_var_int]
	Warning: could not find nodal variable 46 in file id 65536
	NetCDF: Variable not found
```

and as before:

```
Exodus Library Warning/Error: [ex_put_variable_param] in file 'ccx.exo'
	ERROR: nodal variable name parameters are already defined in file id 65536
	NetCDF: String match to name in use
```

and:

```
Exodus Library Warning/Error: [ex_get_time] in file 'ccx.exo'
	ERROR: there are no time_steps on the file id 65536
```
