### ISSUE TITLE
mpi headers installed?

### ISSUE THREAD

**Issue by nschloe** [gsjaardema/seacas#14]
When checking the output of

```
make install
```

[I see](https://launchpadlibrarian.net/223848455/buildlog_ubuntu-wily-amd64.seacas_15.10~201510311137-wily1_BUILDING.txt.gz) that MPI files are installed by SEACAS:

```
-rw-r--r-- root/root      8165 2015-10-31 10:37 ./usr/include/mpi.h
-rw-r--r-- root/root       882 2015-10-31 10:37 ./usr/include/mpi_config.h
-rw-r--r-- root/root      7855 2015-10-31 10:37 ./usr/include/mpi_implementation.h
-rw-r--r-- root/root     21197 2015-10-31 10:37 ./usr/include/mpi_profile.h
-rw-r--r-- root/root     20831 2015-10-31 10:37 ./usr/include/mpi_prototypes.h
```

This should be fixed. If those aren't actually MPI files, they should at least be prefixed with `seacas_` or `seacas/`.

**Comment by rppawlo** [comment]
We just had a user get burned by this. The mpi files are coming from zoltan. If zoltan (or seacas) is built in serial, then zoltan enables a fake MPI library called siMPI so that they don't have to ifdef out mpi calls in their code base for serial builds. siMPI provides a serial back end that I believe are mostly no-ops. The Drekar use case allows seacas to be built and installed in serial, but Drekar is parallel and requires MPI. So the Drekar/Trilinos build was accidentally finding and including the siMPI installed header (mpi.h) instead of the true MPI header (cmake path search), resulting in failures. If a code using seacas requires MPI, you need to build seacas (and thus zoltan) with MPI enabled. Perhaps a good fix is to set the default flag to enable zoltan in seacas to "on" for parallel builds and "off" for serial builds. cc'ing zoltan dev @kddevin

**Comment by gsjaardema** [comment]
I need zoltan on in seacas for serial builds.
..Greg

**Comment by kddevin** [comment]
@rppawlo  thanks for bringing this issue to my attention.
You have diagnosed the problem correctly.  I could investigate whether it would be difficult to change the include file names from our serial MPI.  But it wouldn't get done until next month, at the earliest.  What is your timeframe?

**Comment by kddevin** [comment]
@trilinos/zoltan

**Comment by rppawlo** [comment]
@kddevin No rush on our side. We changed all our build/test scripts to always build parallel seacas tools and will add a section to our build instructions warning users. It might be more of a priority for @nschloe though for debian installation.

**Comment by nschloe** [comment]
At the moment, we simply don't include SEACAS in the Debian build.

**Comment by gsjaardema** [comment]
Instead of changing include file names, it may be best to change the location where they are installed (which was one of Nico's suggestions).  Perhaps install in include/siMPI/mpi.h instead of include/mpi.h and then have the seacas or Trilinos build system add the correct include path based on whether this is a parallel or serial build.

**Comment by kddevin** [comment]
@nschloe I admit I don't understand the target for the debian build.  Is it a strictly serial build?

**Comment by nschloe** [comment]
@kddevin The CMake configure line in [1] contains
```
  -DBUILD_SHARED_LIBS:BOOL=ON \
  -DHDF5_ROOT:PATH=/usr/ \
  -DSEACAS_ENABLE_ALL_PACKAGES:BOOL=ON \
  -DSEACAS_ENABLE_TESTS:BOOL=OFF \
  -DSEACAS_USE_GNUINSTALLDIRS:BOOL=ON \
  -DTPL_ENABLE_CGNS:BOOL=OFF \
  -DTPL_ENABLE_Matio:BOOL=ON \
  -DTPL_ENABLE_METIS:BOOL=ON \
  -DTPL_ENABLE_ParMETIS:BOOL=ON \
  -DTPL_ENABLE_Netcdf:BOOL=ON \
  -DTPL_ENABLE_MPI:BOOL=OFF \
  -DTPL_ENABLE_Pamgen:BOOL=OFF \
  -DTPL_ENABLE_X11:BOOL=OFF \
  -DTPL_ENABLE_Zlib:BOOL=ON
```
so you're right: This is a serial build. (Note though that the the log is almost a year and a half old; I haven't been able to build at all recently because of [compile errors from Zoltan](https://github.com/gsjaardema/seacas/issues/68)).

[1] https://launchpadlibrarian.net/223848455/buildlog_ubuntu-wily-amd64.seacas_15.10~201510311137-wily1_BUILDING.txt.gz

**Comment by gsjaardema** [comment]
I modified the siMPI that SEACAS is using to install the mpi-related headers in a siMPI subdirectory of the specified include directory.  This is not done in the Trilinos or other builds of siMPI; currently only SEACAS.

Will use this in SEACAS only for awhile to see if there are any issues caused by this; if none found then will generate a pull-request for the siMPI in Trilinos.
