### ISSUE TITLE
ex__id_lkup warning given when reading a file

### ISSUE THREAD

**Issue by rms7326** [gsjaardema/seacas#186]
This happens warning happens with my application and also with the example-read.c program in the Exodus source tree. I am able to read the volume.e file but when I attempt to read volume.e.8.0 using my application or the example-read.c program, a warning from the Exodus library is issued when the example code calls ex_get_elem_block (line 147 of packages/seacas/doc-source/exodus/example-read.c) for the first block. In addition, it returns "NULL" for the elem_type name. The second block returns "Hex8". Is there something wrong with the datafile or should I not be asking for the block type because of some other property I should be looking at first.
The warning from the library is:
Exodus Library Warning: ex__id_lkup

[volume_data.zip](https://github.com/gsjaardema/seacas/files/5066311/volume_data.zip)

**Comment by gsjaardema** [comment]
The volume.e.8.0 looks like it is the output from processor 0 in an 8-processor parallel run.  In this decomposition, there are no elements from element block 1 that exist on this processor.  Due to the way exodus stores data in NetCDF (the underlying data format), we cannot store 0-length items on a NetCDF file, so there is no place to store the type (Hex) of the elements that are in the empty element block.  

We do try to make as much metadata as possible consistent between each of the "file-per-processor" (fpp) output files and each file is a valid exodus file; however, there is some strangeness in accessing the fpp files individually.    For general postprocessing, we typically "join" the individual fpp files into a single file using `epu`

It is possible to read the individual files, but there will be warnings when you access emtpy blocks or sets.

**Comment by rms7326** [comment]
Thank you for that explanation, that makes a lot of sense.
