### ISSUE TITLE
Bring back exodus tar files

### ISSUE THREAD

**Issue by nncarlson** [gsjaardema/seacas#31]
I'm dismayed to find the Exodus release tar files have been purged from sourceforge.  Are these archived somewhere else?  I'd be looking for the last one made, I suppose.  The seacas package is *way too big* to be including as a distributed TPL when all that is wanted is exodus.

**Comment by gsjaardema** [comment]
I will look into options.

**Comment by gsjaardema** [comment]
There is now a "exodus" branch.  If you switch to that branch and then click the "Download Zip" button, you should get only the exodus portion of the repository (and the tribits build stuff).  This isn't the same as the old exodus tar file since exodus is buried down in the hierarchy (packages/seacas/libraries/exodus), but does remove most of the other stuff you didn't want.  I will look into removing more of the tribits-cmake code to reduce the size further.

Hope this works for you.

**Comment by gsjaardema** [comment]
The direct link should be https://github.com/gsjaardema/seacas/archive/exodus.zip

**Comment by nncarlson** [comment]
Thanks!  I'm giving it a go this weekend.

**Comment by nncarlson** [comment]
This works for me, thanks!
